<?php

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::NONE_LEVEL)
    ->setUsingCache(true)
    ->fixers([
        'concat_with_spaces',
        'duplicate_semicolon',
        'elseif',
        'empty_return',
        'encoding',
        'eof_ending',
        'function_call_space',
        'include',
        'indentation',
        'line_after_namespace',
        'linefeed',
        'lowercase_constants',
        'lowercase_keywords',
        'method_argument_space',
        'multiline_array_trailing_comma',
        'multiple_use',
        'namespace_no_leading_whitespace',
        'object_operator',
        'operators_spaces',
        'ordered_use',
        'parenthesis',
        'php_closing_tag',
        'psr0',
        'remove_leading_slash_use',
        'remove_lines_between_uses',
        'short_array_syntax',
        'single_array_no_trailing_comma',
        'spaces_before_semicolon',
        'spaces_cast',
        'standardize_not_equal',
        'ternary_spaces',
        'trailing_spaces',
        'unused_use',
        'visibility',
        'whitespacy_lines',
    ])
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->in(__DIR__)
            ->exclude([
                'app',
                'web',
                'vendor',
            ])
            ->notPath('src/Korobi/WebBundle/Resources/views/controller/generic/style_guide.html.twig')
    );
