services:
    # -------------------------
    # ---- Twig Extensions ----
    # -------------------------
    korobi.extension.twig.globals:
        class: Korobi\WebBundle\Extension\ExtensionTwigGlobals
        tags:
            - { name: twig.extension }
        arguments:
            - @korobi.git_info
    korobi.extension.twig.filters:
        class: Korobi\WebBundle\Extension\ExtensionTwigFilters
        tags:
            - { name: twig.extension }
    korobi.extension.twig.functions:
        class: Korobi\WebBundle\Extension\ExtensionTwigFunctions
        tags:
            - { name: twig.extension }
    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: [@translator]
        tags:
          - { name: twig.extension }

    # ---------------------
    # ---- Controllers ----
    # ---------------------
    korobi.base_controller:
        class: Korobi\WebBundle\Controller\BaseController
        calls:
            - [setContainer, ["@service_container"]]
    korobi.controller.security:
        class: Korobi\WebBundle\Controller\SecurityController
        parent: korobi.base_controller
        arguments:
            - @korobi.akio
            - @logger
    korobi.controller.deploy:
        class: Korobi\WebBundle\Controller\DeploymentController
        parent: korobi.base_controller
        arguments:
            - @logger
            - @korobi.git_info
            - @korobi.akio
        calls:
            - [setHmacKey, ["%github_hook_hmac_secret%"]]
            - [setRootPath, ["%kernel.root_dir%"]]

    # ---------------------------
    # ---- Helpers/Utilities ----
    # ---------------------------
    korobi.git_info:
        class: Korobi\WebBundle\Util\GitInfo
    korobi.navigation_collection:
        class: Korobi\WebBundle\Util\NavigationCollection
        arguments:
            - %korobi.config%
    korobi.theme_service:
        class: Korobi\WebBundle\Util\ThemeService
        arguments:
            - @session
    korobi.akio:
        class: Korobi\WebBundle\Util\Akio
        arguments:
            - %akio_enabled%
            - %akio_path%
            - %akio_key%
    korobi.influx:
        class: Korobi\WebBundle\Util\InfluxService
        arguments:
            - %influx_host%
            - %influx_port%
            - %influx_user%
            - %influx_pass%
            - %influx_db%

    # ----------------------------
    # ----- Console commands -----
    # ----------------------------
    korobi.command.stats_gen:
        class: Korobi\WebBundle\Console\StatsGeneration
        arguments:
            - @korobi.influx
        tags:
            -  { name: console.command }
