<?php

namespace Korobi\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelViewKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelViewKeyRepository extends EntityRepository {
}
